CREATE TABLE TODOLIST
(
    ID          SERIAL       NOT NULL,
    NAME        VARCHAR(20)  NOT NULL,
    DESCRIPTION VARCHAR(120) NOT NULL,
    DEADLINE    TIMESTAMP WITH TIME ZONE,
    PRIORITY    INT          NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (NAME)
);

select *
from TODOLIST;